import turtle
olym = turtle.Pen()
olym.penup()
olym.backward(250)
olym.left(90)
olym.forward(300)
olym.left(90)
olym.pendown()
olym.pensize(6)
olym.color("blue")
olym.circle(50)
olym.left(90)
olym.penup()
olym.forward(100)
olym.left(90)
olym.forward(110)
olym.left(90)
olym.pendown()
olym.color("yellow")
olym.circle(50)
olym.penup()
olym.right(90)
olym.forward(60)
olym.left(90)
olym.forward(50)
olym.pendown()
olym.color("black")
olym.circle(50)
olym.penup()
olym.right(90)
olym.forward(10)
olym.right(90)
olym.forward(100)
olym.left(90)
olym.pendown()
olym.color("LimeGreen")
olym.circle(50)
olym.penup()
olym.forward(60)
olym.left(90)
olym.forward(50)
olym.right(90)
olym.pendown()
olym.color("Red")
olym.circle(50)


